# Project information
site_name: QField Ecosystem Documentation
site_url: https://qfield.org/
site_author: OPENGIS.ch
site_description: >-
  QField Documentation site

# Repository
repo_name: opengisch/qfield
repo_url: https://github.com/opengisch/qfield
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 OPENGIS.ch

# Configuration
theme:
  name: material
  custom_dir: theme_overrides/
  features:
    - navigation.tabs
    - search.suggest
  logo: assets/images/qfield_logo.svg
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
    - scheme: slate
      primary: blue
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

# Page tree
nav:
  - Home:
      - Welcome: index.md
#      - Case Studies:
#          - sss.md
      - support.md
  - QField:
      - qfield/concepts.md
      - qfield/installation.md
      - Prepare for Work:
          - qfield/prepare/hiding-legend.md
          - qfield/prepare/attribute-form.md
          - qfield/prepare/map-styling.md
          - qfield/prepare/map-themes.md
          - qfield/prepare/display-expression.md
          - qfield/prepare/1-n-pictures.md
          - qfield/prepare/picture-path.md
          - qfield/prepare/print.md
          - qfield/prepare/custom-svg.md
          - qfield/prepare/advanced.md
      - Synchronization:
          - ppp.md
      - Fieldwork:
          - ppp.md
      - Getting Started Tutorials:
          - ppp.md
      - Supported Data Formats:
          - ppp.md
  - QFieldCloud:
      - qfieldcloud/concepts.md
      - User Manual:
          - eeee.md
      - Development:
          - qfieldcloud/dev/system.md
          - qfieldcloud/dev/permissions.md
          - qfieldcloud/dev/storage.md
          - qfieldcloud/dev/web.md
      - API Reference:
          - qfieldcloud/api/v1.md
          - api/v2.md
  - QFieldSync:
      - qfieldsync/main.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - fancyboxmd
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Css
extra_css:
  - stylesheets/extra.css
  - stylesheets/jquery.fancybox.min.css

# Extra javascript
extra_javascript:
  - javascript/jquery.min.js
  - javascript/jquery.fancybox.min.js

extra:
  # Remove "Made with Material for MkDocs" from footer
  generator: false
  # Languages. Don't add translated content into this repo It will be
  # added by github ci based on transifex translations.
  alternate:
    - name: English
      link: https://opengisch.github.io/mkdocs_test/en/
      lang: en
    - name: Italiano
      link: https://opengisch.github.io/mkdocs_test/it/
      lang: it
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opengisch
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opengisch
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opengisch/
