# Project information
site_name: QField Ecosystem Documentation
site_url: https://qfield.org/
site_author: OPENGIS.ch
site_description: >-
  QField Documentation site

# Repository
repo_name: opengisch/qfield
repo_url: https://github.com/opengisch/qfield
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 OPENGIS.ch

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
  logo: assets/images/qfield_logo.svg
  favicon: assets/images/favicon.ico
  palette:
    primary: green

# Page tree
nav:
  - Home:
      - Welcome: index.md
#      - Case Studies:
#          - sss.md
      - support.md
  - QField:
      - qfield/concepts.md
      - qfield/installation.md
      - Prepare for Work:
          - qfield/prepare/hiding-legend.md
          - qfield/prepare/attribute-form.md
          - qfield/prepare/map-styling.md
          - qfield/prepare/map-themes.md
          - qfield/prepare/display-expression.md
          - qfield/prepare/1-n-pictures.md
          - qfield/prepare/picture-path.md
          - qfield/prepare/print.md
          - qfield/prepare/custom-svg.md
          - qfield/prepare/advanced.md
      - Synchronization:
          - ppp.md
      - Fieldwork:
          - ppp.md
      - Getting Started Tutorials:
          - ppp.md
      - Supported Data Formats:
          - ppp.md
  - QFieldCloud:
      - qfieldcloud/concepts.md
      - User Manual:
          - eeee.md
      - Development:
          - qfieldcloud/dev/system.md
          - qfieldcloud/dev/permissions.md
          - qfieldcloud/dev/storage.md
          - qfieldcloud/dev/web.md
      - API Reference:
          - qfieldcloud/api/v1.md
          - api/v2.md
  - QFieldSync:
      - qfieldsync/main.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Css
extra_css:
  - stylesheets/extra.css
  - stylesheets/jquery.fancybox.min.css

# Extra javascript
extra_javascript:
  - javascript/jquery.min.js
  - javascript/jquery.fancybox.min.js
