* mkdocs test
  Repo to test the creation of documentation using [[https://www.mkdocs.org/][mkdocs]] with the great [[https://squidfunk.github.io/mkdocs-material/][material theme]].

** Local development
   Install and run local server
   #+begin_src sh
     pipenv install
     pipenv shell
     mkdocs serve
   #+end_src

   The page is on [[http://localhost:8000]]. It is autoreloaded on changes.
** Insiders version
   It's not necessary that you have the insiders version installed
   locally to create the documentation content. But if you want to use
   the insiders only features locally, you should uninstall
   `mkdocs-material` from your pipenv and install it using the private
   fork of the insiders repo in the opengisch organization (of course
   you need access to the opengisch organization and an access token):

   #+begin_src sh
     pipenv uninstall mkdocs-material
     pipenv install -v git+https://YOUR_GITHUB_USERNAME:YOUR_GITHUB_TOKEN@github.com/opengisch/mkdocs-material-insiders#egg=mkdocs-material
   #+end_src

   Remember to not commit you pipenv file with your Github token.
** Deployment
   There is a Github action that deploys automatically at every push the site on [[https://opengisch.github.io/mkdocs_test/]]
** Translations
   Only the English version is present in the repository. The other
   ones are generated in the CI, downloading the content from
   Transifex.
