name: ci
on:
  push:
    branches:
      - master
      - insiders

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install https://marioba:${{ secrets.GH_TOKEN }}@github.com/opengisch/mkdocs-material-insiders#egg=mkdocs-material
      - run: pip install mkdocs-material fancyboxmd
      - run: mkdocs gh-deploy --force
